[package]
name = "fenster"
version = "0.1.1"
authors = ["The Tremor Team"]
edition = "2018"
license = "Apache-2.0"
description = "Simple sliding window implementation"


[dependencies]
chrono = "0.4"

[dev-dependencies]
proptest = "1.4.0"
